apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oa6vl7o81-go
  janus-idp.io/tekton: oa6vl7o81-go
  backstage.io/kubernetes-id: oa6vl7o81-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oa6vl7o81-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
